layout_spectrum: 0.9857737629208714
typography_spectrum: 0.5197975907940418
color:
  brandStrength: 0.0966179755050689
  lightness: 0.9021974424831569
  saturation: 0.5332280134316534
  rhythmicContrast: 0.17567343055270612
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
content_rating:
  adult: false
opengraph:
  appId: www.facebook.com/kiteonair
name: KiteOnAir
navigation:
  - name: they say..
    url: >-
      http://www.margeye.com/2015/01/20/stefano-brought-by-the-wind-to-indonesia-and-to-gili-air-stefano-porte-par-le-vent-en-indonesie-et-a-gili-air/
    type: external
  - name: KiteOnAir.com
    url: 'http://kiteonair.com'
    type: external
  - name: Project
    url: 'http://kiteonair.com/project/index.html'
    type: external
title: 'Kites rise highest against the wind, not with it.'
description: Talaimannar Sri Lanka
