layout_spectrum: 0.8683888663072139
typography_spectrum: 0.9470232715830207
color:
  brandStrength: 0.03626192663796246
  lightness: 0.9360938889440149
  saturation: 0.5491921082139015
  rhythmicContrast: 0.9562858487479389
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
content_rating:
  adult: false
opengraph:
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/2b6308a7-da37-43d7-b1b5-28a2deab4e9a.jpg
analytics:
  twitter: www.twitter.com/_kiteonair_
author:
  name: Stefano
  email: info@kiteonair.com
  url: 'http://kiteonair.com'
logo: null
name: KiteOnAir
navigation:
  - name: they say..
    url: >-
      http://www.margeye.com/2015/01/20/stefano-brought-by-the-wind-to-indonesia-and-to-gili-air-stefano-porte-par-le-vent-en-indonesie-et-a-gili-air/
    type: external
  - name: Project
    url: 'http://kiteonair.com/project/index.html'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b0924e12-4c60-413e-9bdb-5f9597f17a51.jpg
title: 'Kites rise highest against the wind, not with it.'
description: Talaimannar Sri Lanka
