typography_spectrum: 0.05074034072458744
content_rating:
  adult: false
color:
  brandStrength: 0.86586689716205
  lightness: 0.4694842076860368
  saturation: 0.006285388022661209
  rhythmicContrast: 0.2018368667922914
  brandColors:
    - '#526F8F'
    - '#7A92AA'
    - '#B5B6B0'
    - '#666342'
    - '#305572'
opengraph:
  appId: www.facebook.com/kiteonair
layout_spectrum: 0.38264186843298376
name: KiteOnAir
navigation:
  - name: our main web site
    url: www.kiteonair.com
    type: external
title: 'Kites rise highest against the wind, not with it.'
description: Talaimannar Sr Lanka
