layout_spectrum: 0.9141020975075662
typography_spectrum: 0.7615269089583308
color:
  brandStrength: 0.0325803067535162
  lightness: 0.42349627218209207
  saturation: 0.5775141688063741
  rhythmicContrast: 0.43049761187285185
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
content_rating:
  adult: false
opengraph:
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/2b6308a7-da37-43d7-b1b5-28a2deab4e9a.jpg
analytics:
  twitter: www.twitter.com/_kiteonair_
author:
  name: Stefano
  email: info@kiteonair.com
  url: 'http://kiteonair.com'
logo: null
name: KiteOnAir
navigation:
  - name: they say..
    url: >-
      http://www.margeye.com/2015/01/20/stefano-brought-by-the-wind-to-indonesia-and-to-gili-air-stefano-porte-par-le-vent-en-indonesie-et-a-gili-air/
    type: external
  - name: Project
    url: 'http://kiteonair.com/project/index.html'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b0924e12-4c60-413e-9bdb-5f9597f17a51.jpg
title: 'Kites rise highest against the wind, not with it.'
description: Talaimannar Sri Lanka
